version: '3.7'

services:

  proxy:
    image: nginx:latest   # 최신 버전의 Nginx 사용
    container_name: proxy # container 이름은 proxy
    ports: 
      - "80:80"           # 80번 포트를 host와 container 맵핑
      - "443:443"           # 80번 포트를 host와 container 맵핑
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf # nginx 설정 파일 volume 맵핑
      - /etc/nginx/ssl
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - server-node
    networks:
      - node_nginx
    restart: "unless-stopped" # 내부에서 에러로 인해 container가 죽을 경우 restart


  server-node:
    container_name: server-node
    build:
      context: ./diary-backend
      dockerfile: Dockerfile
    command: tail -f /dev/null
    environment:
      TZ: "Asia/Seoul" 
    volumes:
      - ./diary-backend:/usr/src/app
    ports:
      - '3000:3000'
    links:
      - postgresql
    depends_on:
      - postgresql
    networks:
      - node_nginx
      - backend
    restart: 'unless-stopped'
    
  postgresql:
    image: postgres
    container_name: postgresql
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      TZ: "Asia/Seoul" 
    ports:
      - '5432:5432'
    networks:
      - backend

networks:
  node_nginx:
    driver: bridge
  backend:
    driver: bridge

volumes:
  data:
    driver: local
